version: '3.1'

services:
  tz:
    container_name: calc_formula
    restart: always
    build:
      context: .
    ports:
      - '8888:8888'
    volumes:
      - ./:/tz/



networks:
  default:
    internal: true
