# Generated by Django 4.2.6 on 2023-10-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0004_alter_formulavalidator_formula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulavalidator',
            options={'ordering': ('-id',), 'verbose_name': 'Формула', 'verbose_name_plural': 'Формулы'},
        ),
    ]
